"""File guard (PreToolUse on Read, Write, Edit, MultiEdit, NotebookEdit; runs
in the main session and inside subagents alike): keeps agents inside the
token and ownership rules that CLAUDE.md already states in prose.

- Read of a binary or cache file (images, audio fonts, .import, anything
  under .godot/ or __pycache__/) never earns its cost back; the caller
  should list the folder for names instead (CLAUDE.md Token budget).
- Read of a text file over 300 lines without an offset and a limit of at
  most 300 would load the whole thing into context; grep -n for the symbol
  and read around it instead (same rule).
- Generated and tool-owned files (the boon resources and icons, the
  project map, the smoke fingerprint, the scene dump, anything Godot itself
  writes, the owner's export presets, the try/smoke override.cfg) each have
  a generator or an owner; a hand edit is either overwritten by the next
  run or silently drifts from what reads it.
- In the main session (no agent_id), source files are the implementer
  subagent's job, built from a spec (CLAUDE.md Main session role); the main
  session itself may still make a single-line Edit. A Fable session
  implements directly (CLAUDE.md Main session role), so this rule skips
  it; the model is read from the transcript's tail.
- A Write or (Multi)Edit that changes an id=, unique_id= or uid:// value on
  an existing .tscn/.tres header line is refused for every caller: those
  values are referenced by id elsewhere in the file and by other files, and
  renumbering one breaks every reference to it.

Never fails the hook: any error allows the call (exit 0).
"""
import fnmatch
import json
import os
import re
import sys

BINARY_SUFFIXES = {
    ".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tga", ".exr", ".hdr",
    ".wav", ".ogg", ".mp3", ".import", ".ttf", ".otf", ".woff", ".woff2",
    ".glb", ".fbx", ".blend", ".res", ".scn", ".ctex", ".pck", ".zip",
    ".exe", ".dll", ".so", ".pyc",
}
CACHE_DIR_NAMES = {".godot", "__pycache__"}
SOURCE_SUFFIXES = {".gd", ".tscn", ".tres", ".gdshader", ".gdshaderinc", ".py", ".cfg"}
WRITE_TOOLS = {"Write", "Edit", "MultiEdit", "NotebookEdit"}

MAX_LINES = 300
MAX_READ_BYTES = 50 * 1024 * 1024
TRANSCRIPT_TAIL_BYTES = 400_000

# Matches an existing id=, unique_id= or uid:// value on a .tscn/.tres
# header line, so two headers can be compared with those values masked out.
TOKEN = re.compile(r'\b(?:id="[^"]*"|unique_id=\d+|uid="uid://[^"]*")')
MODEL_RE = re.compile(r'"model"\s*:\s*"([^"]+)"')


def ext(path: str) -> str:
    return os.path.splitext(path)[1].lower()


def find_root(path: str) -> str | None:
    # walk up from the file's folder to the first project.godot; a file
    # outside any Godot checkout (scratchpad, another project) allows.
    d = os.path.dirname(path)
    while True:
        if os.path.isfile(os.path.join(d, "project.godot")):
            return d
        parent = os.path.dirname(d)
        if parent == d:
            return None
        d = parent


def deny(reason: str) -> None:
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "deny",
        "permissionDecisionReason": reason,
    }}))


def read_violation(path: str, rel: str, tool_input: dict) -> str | None:
    parts = rel.split("/")
    if ext(path) in BINARY_SUFFIXES or any(p in CACHE_DIR_NAMES for p in parts):
        return (f"{rel} is a binary or cache file; list its folder for "
                 "names only (CLAUDE.md Token budget).")
    if not os.path.isfile(path):
        return None
    if os.path.getsize(path) >= MAX_READ_BYTES:
        return None
    with open(path, "rb") as f:
        data = f.read()
    lines = data.count(b"\n")
    if data and not data.endswith(b"\n"):
        lines += 1
    limit = tool_input.get("limit")
    if lines > MAX_LINES and (limit is None or int(limit) > MAX_LINES):
        return (f"{rel} has {lines} lines. Grep -n for the function, signal "
                 "or node you need, then Read with offset and a limit of "
                 "at most 300 (CLAUDE.md Token budget).")
    return None


def generated_reason(rel: str) -> str:
    # First hit wins; the table is ordered because that's how the spec that
    # produced it reads, not because any two patterns here can both match.
    if (fnmatch.fnmatchcase(rel, "resources/items/boons/*.tres")
            or rel in ("resources/items/pools/general_boon_pool.tres",
                       "resources/items/pools/warehouse_rare_boon_pool.tres")):
        return ("generated by tools/generate_boons.py: change the "
                 "generator, then run py -3 tools/generate_boons.py")
    if fnmatch.fnmatchcase(rel, "scenes/items/boons/*.svg"):
        return ("generated by tools/generate_boon_icons.py: change it, "
                 "then run py -3 tools/generate_boon_icons.py")
    if rel == "docs/PROJECT_MAP.md":
        return "generated: run py -3 tools/gen_context.py"
    if rel in ("tools/smoke/fingerprint.txt", "tools/smoke/fingerprint.baseline.txt"):
        return ("written by py -3 tools/smoke.py (--bless rewrites the "
                 "baseline, only when a change is meant to alter the "
                 "fingerprint)")
    if rel in ("tools/scene_dump/van.txt", "tools/scene_dump/van.baseline.txt"):
        return ("written by py -3 tools/scene_dump.py (--bless only when "
                 "the van tree is meant to change)")
    if (fnmatch.fnmatchcase(rel, "*.import") or fnmatch.fnmatchcase(rel, "*.uid")
            or ".godot" in rel.split("/")):
        return ("written by Godot: py -3 tools/check.py writes missing "
                 ".gd.uid files; move a script together with its .gd.uid")
    if rel == "export_presets.cfg":
        return "the owner's local export settings; never touch it"
    if rel == "override.cfg":
        return ("written by tools/try.py and tools/smoke.py --shots for a "
                 "single run; never edit or commit it")
    return ""


def session_model(transcript_path: str | None) -> str:
    # Last "model" field logged in the transcript's tail, or "" on any
    # problem (no path, unreadable file, no match).
    if not transcript_path:
        return ""
    try:
        with open(transcript_path, "rb") as f:
            f.seek(0, os.SEEK_END)
            size = f.tell()
            f.seek(max(0, size - TRANSCRIPT_TAIL_BYTES))
            data = f.read()
    except OSError:
        return ""
    text = data.decode("utf-8", errors="ignore")
    matches = MODEL_RE.findall(text)
    return matches[-1] if matches else ""


def edit_pairs(tool_name: str, tool_input: dict) -> list[tuple[str, str]]:
    if tool_name == "Edit":
        return [(tool_input.get("old_string", ""), tool_input.get("new_string", ""))]
    if tool_name == "MultiEdit":
        edits = tool_input.get("edits") or []
        return [(e.get("old_string", ""), e.get("new_string", "")) for e in edits]
    return []


def main_session_violation(tool_name: str, tool_input: dict) -> bool:
    if tool_name == "Write":
        return True
    if tool_name == "Edit":
        old = tool_input.get("old_string", "")
        new = tool_input.get("new_string", "")
        return bool("\n" in old.strip("\n") or "\n" in new.strip("\n")
                     or tool_input.get("replace_all"))
    if tool_name == "MultiEdit":
        edits = tool_input.get("edits") or []
        if len(edits) > 1:
            return True
        return any("\n" in e.get("old_string", "").strip("\n")
                   or "\n" in e.get("new_string", "").strip("\n") for e in edits)
    if tool_name == "NotebookEdit":
        return True
    return False


def header_lines(text: str) -> list[str]:
    return [line for line in text.splitlines() if line.strip().startswith("[")]


def scene_id_violation(old_string: str, new_string: str) -> str | None:
    # A header line's id/unique_id/uid changed if, once those values are
    # masked out, it matches another header that differs from it verbatim.
    # A header whose path= also changed stays unequal after masking, so
    # repointing a resource to a different file is still allowed.
    for old in header_lines(old_string):
        if not TOKEN.search(old):
            continue
        masked_old = TOKEN.sub("#", old)
        for new in header_lines(new_string):
            if TOKEN.sub("#", new) == masked_old and new != old:
                return (f"This edit changes an id on an existing header line:\n"
                         f"{old.strip()}\n-> {new.strip()}\nNever change or "
                         "renumber existing id=, unique_id= or uid:// values; "
                         "new ids must not collide with ids already in the file.")
    return None


def main() -> None:
    d = json.load(sys.stdin)
    tool_name = d.get("tool_name") or ""
    tool_input = d.get("tool_input") or {}
    path = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not path:
        return
    cwd = d.get("cwd") or os.getcwd()
    if not os.path.isabs(path):
        path = os.path.join(cwd, path)
    path = os.path.abspath(path)

    root = find_root(path)
    if root is None:
        return
    rel = os.path.relpath(path, root).replace("\\", "/")

    if tool_name == "Read":
        reason = read_violation(path, rel, tool_input)
        if reason:
            deny(reason)
        return

    if tool_name not in WRITE_TOOLS:
        return

    why = generated_reason(rel)
    if why:
        deny(f"{rel} is {why}.")
        return

    if (not d.get("agent_id")
            and (ext(path) in SOURCE_SUFFIXES or rel == "project.godot")
            and "fable" not in session_model(d.get("transcript_path")).lower()
            and main_session_violation(tool_name, tool_input)):
        deny("Main session: source files (.gd .tscn .tres .gdshader .py "
             ".cfg project.godot) are changed by the implementer subagent "
             "from a spec (CLAUDE.md Main session role). The only "
             "exception is a single-line Edit.")
        return

    if tool_name in ("Edit", "MultiEdit") and ext(path) in (".tscn", ".tres"):
        for old, new in edit_pairs(tool_name, tool_input):
            reason = scene_id_violation(old, new)
            if reason:
                deny(reason)
                return


try:
    main()
except Exception:
    pass
